### ISSUE TITLE
Can't build with 7.10.3 GHCJS snapshot

### ISSUE THREAD

**Issue by bitemyapp** [dmjio/miso#145]
```
/home/callen/work/miso/ghcjs-src/Miso/Effect/XHR.hs:96:15:
    Not in scope: type constructor or class ‘CaptureAll’
    Perhaps you meant ‘Capture’ (imported from Servant.API)
               
/home/callen/work/miso/ghcjs-src/Miso/Effect/XHR.hs:97:13:
    Not in scope: type constructor or class ‘CaptureAll’
    Perhaps you meant ‘Capture’ (imported from Servant.API)
Completed 28 action(s).

--  While building package miso-0.1.0.4 using:
      /home/callen/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.0.0_ghcjs-0.2.0.9006020_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0_ghcjs build lib:miso --ghcjs-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by dmjio** [comment]
@bitemyapp Ah, the stack file must provide a version of servant before `CaptureAll` was added, will probably need CPP for this. 

- What does `ghcjs-list pkg | grep servant` show? 
- Are those the only two errors?
- Are you using the stack file in this repo?

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/146

**Comment by bitemyapp** [comment]
```
$ stack exec ghcjs-pkg list | grep servant
    servant-0.7.1
```

**Comment by dmjio** [comment]
@bitemyapp big thanks, check out `0.1.1.0` on hackage. 
` stack build --flag miso:examples`

If not building with `nix`, the static assets (image files and html) for the examples will need to be manually copied into the correct locations. This is true for `mario` and `todo-mvc`, no additional changes for `simple`. Please re-open this issue if problems persist.

**Comment by bitemyapp** [comment]
![screenshot from 2017-07-03 20-04-49](https://user-images.githubusercontent.com/320177/27811344-dff27cec-602a-11e7-8b35-11c347b1b2a8.png)

**Comment by dmjio** [comment]
👌
